name: Build and Deploy to GKE

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build and push
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_IMAGE_LABEL }}:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_IMAGE_LABEL }}:${{ github.sha }}

      - name: "deploy"
        run: |
          gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --region ${{ secrets.GCP_PROJECT_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}
          sed -i 's/${{ secrets.GCP_IMAGE_LABEL }}:latest/${{ secrets.GCP_IMAGE_LABEL }}:${{ github.sha }}/g' deployment.yaml
          kubectl apply -f deployment.yaml

      # - name: Get Config
      #   run: |
      #     mkdir ${HOME}/.kube
      #     echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
      #     cat ${HOME}/.kube/config

      # - uses: danielr1996/kubectl-action@1.0.0
      #   name: Deploy
      #   with:
      #     kubeconfig: ${{ secrets.KUBE_CONFIG }}
      #     args: apply -f deployment.yaml

      # - name: Use context
      #   run: |
      #     kubectl config use-context gke_rocket-346418_us-central1_rocket-push
      #     kubectl config view

      # - name: Deploy to K8s
      #   run: kubectl get pods

      # - uses: azure/k8s-set-context@v2
      #   with:
      #     method: kubeconfig
      #     kubeconfig: ${{ secrets.KUBE_CONFIG }}
      #   id: login
      #     sed -i -e 's/test:lastest/test:${{ github.sha }}/g' ./deployment.yaml
      #     kuberctl apply -f deployment.yaml
