---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  namespace: default
  labels:
    app: {{ .Values.app_name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
        - name: {{ .Values.app_name }}
          image: gcr.io/{{ .Values.projectId }}/{{ .Values.image_label }}:{{ .Values.image_tag }}
          ports:
            - containerPort: {{ .Values.target_port }}
              name: {{ .Values.app_name }}
