---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
  namespace: default
  labels:
    app: {{ .Values.app_name }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.target_port }}
  selector:
    app: {{ .Values.app_name }}
  type: LoadBalancer
  loadBalancerIP: ""