on:
  workflow_call:
    secrets:
      GCP_CREDENTIALS:
        required: true
env:
  GCP_PROJECT_ID: rocket-346418
  GCP_IMAGE_LABEL: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add environments variables to .env file
        run: |
          echo "SHOPIFY_API_KEY=1bb9dc9b06252cd34c867d4f3a115027" >> .env
          echo "SHOPIFY_API_SECRET=${{ secrets.SHOPIFY_API_SECRET }}" >> .env
          echo "SHOP=abandoned-cart-dev.myshopify.com" >> .env
          echo "SCOPES=write_products,write_customers,write_draft_orders,write_checkouts,write_files,write_script_tags,write_themes" >> .env
          echo "HOST=https://teqie.ml" >> .env

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build and push
        run: |
          docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_IMAGE_LABEL }}:${{ github.sha }} .
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_IMAGE_LABEL }}:${{ github.sha }}
